services:
  quiz-app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../..:/workspace
      - /workspace/frontend/node_modules
    working_dir: /workspace/frontend
    environment:
      - NODE_ENV=development
      - REACT_APP_ENV=development
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    stdin_open: true
    tty: true 